#
# This file is autogenerated by the Scene Manager plugin.
# DO NOT EDIT.
#
@tool
extends Node

# [Scene Enum]
enum SceneName \
{ 
	NONE = -1, 
	LOADING, 
	LOADING_WITH_INITIALIZATION, 
	SCENE1, 
	SCENE2, 
	SCENE3, 
	SCENE_WITH_LOADING_PHASE, 
}

# [Scene Dictionary]
var scenes: Dictionary = \
{
	"_include_list": [
		"res://demo"
	],
	"_scenes": {
		"loading": {
			"sections": [],
			"value": "res://demo/loading.tscn"
		},
		"loading_with_initialization": {
			"sections": [],
			"value": "res://demo/loading_with_initialization.tscn"
		},
		"scene1": {
			"sections": [
				"Level"
			],
			"value": "res://demo/scene1.tscn"
		},
		"scene2": {
			"sections": [
				"Level"
			],
			"value": "res://demo/scene2.tscn"
		},
		"scene3": {
			"sections": [
				"Level"
			],
			"value": "res://demo/scene3.tscn"
		},
		"scene_with_loading_phase": {
			"sections": [],
			"value": "res://demo/scene_with_loading_phase.tscn"
		}
	},
	"_sections": [
		"Level"
	]
}
# [End Scene Dictionary]
